import cv2
import matplotlib.pyplot as plt
image=cv2.imread("fortniteimage.jpg")
if image is None:
    print("Error: Could not load image")
    exit()
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
plt.imshow(gray,cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")
plt.show()
cv2.imwrite("output_images/grayscale.jpg",gray)
cropped=image[100:300,200:400]
plt.imshow(cv2.cvtColor(cropped,cv2.COLOR_BGR2RGB))
plt.title("Cropped Image")
plt.axis("off")
plt.show()
cv2.imwrite("output_images/cropped.jpg",cropped)
height,width=image.shape[:2]
center=(width//2,height//2)
matrix=cv2.getRotationMatrix2D(center,45,1)
rotated=cv2.warpAffine(image,matrix,(width,height))
plt.imshow(cv2.cvtColor(rotated,cv2.COLOR_BGR2RGB))
plt.title("Rotated Image")
plt.axis("off")
plt.show()
cv2.imwrite("output_images/rotated.jpg",rotated)
brightened=cv2.add(image,50)
plt.imshow(cv2.cvtColor(brightened,cv2.COLOR_BGR2RGB))
plt.title("Brightened Image")
plt.axis("off")
plt.show()
cv2.imwrite("output_images/brightened.jpg",brightened)
print("All images were successfully saved")